# Generated by Django 4.2 on 2023-04-09 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0004_alter_tweet_id_alter_tweet_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='created_at',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_name',
            field=models.TextField(default=None),
        ),
    ]
