# Generated by Django 4.2 on 2023-04-12 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0006_tweet_tweet_id_alter_tweet_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='text',
            field=models.TextField(default=None),
        ),
    ]
