# Generated by Django 4.2 on 2023-04-15 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0007_alter_tweet_id_alter_tweet_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bacapres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default=None)),
                ('keyword', models.TextField(default=None)),
                ('desc', models.TextField(default=None)),
            ],
        ),
    ]
