# Generated by Django 4.2 on 2023-04-16 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0008_bacapres'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sentiment',
            field=models.TextField(default=None),
        ),
    ]
