# Generated by Django 4.2 on 2023-05-02 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0009_tweet_sentiment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bacapres',
            name='keyword',
        ),
        migrations.AlterField(
            model_name='bacapres',
            name='desc',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='bacapres',
            name='name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.CharField(default=None),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='user_name',
            field=models.CharField(default=None),
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=50)),
                ('bacapres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sentiment.bacapres')),
            ],
        ),
    ]
