# Generated by Django 4.2 on 2023-05-02 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0010_remove_bacapres_keyword_alter_bacapres_desc_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Keyword',
            new_name='BacapresKeyword',
        ),
    ]
