# Generated by Django 4.2 on 2023-05-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0012_bacapres_keyword_delete_bacapreskeyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='text_preprocessed',
            field=models.TextField(default=None),
        ),
    ]
