# Generated by Django 4.2 on 2023-05-14 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0014_remove_tweet_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sentiment',
            field=models.TextField(default=None),
        ),
    ]
