# Generated by Django 4.2 on 2023-05-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0015_tweet_sentiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bacapres',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='bacapres_pics'),
        ),
    ]
