# Generated by Django 4.2 on 2023-05-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0016_bacapres_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacapres',
            name='desc',
            field=models.CharField(default=None, null=True),
        ),
    ]
