# Generated by Django 4.2 on 2023-05-17 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0017_alter_bacapres_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacapres',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='static/media/bacapres_pics'),
        ),
    ]
