# Generated by Django 4.2 on 2023-05-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0018_alter_bacapres_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bacapres',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='bacapres_pics/'),
        ),
    ]
