# Generated by Django 4.2 on 2023-05-19 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0019_alter_bacapres_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='bacapres',
            field=models.IntegerField(default=None),
        ),
    ]
