# Generated by Django 4.2 on 2023-05-20 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentiment', '0020_tweet_bacapres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='created_at',
            field=models.DateField(default=None),
        ),
    ]
