# Generated by Django 4.2 on 2023-05-27 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bacapres', '0003_alter_bacapres_avatar'),
        ('sentiment', '0025_alter_history_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='bacapres',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bacapres.bacapres'),
        ),
    ]
