# Generated by Django 4.2 on 2023-06-02 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bacapres', '0004_alter_bacapres_avatar_alter_bacapres_keyword'),
        ('sentiment', '0026_alter_tweet_bacapres'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedTweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_id', models.TextField(default=None)),
                ('text', models.TextField(default=None)),
                ('user_name', models.CharField(default=None)),
                ('created_at', models.DateTimeField(default=None)),
                ('bacapres', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bacapres.bacapres')),
            ],
        ),
    ]
